print("Bienvenido usuario Digite su datos")
nombre=str(input("Digite su nombre "))
apellido=str(input("Digite su apellido "))
correo=str(input("Digite su correo "))
telefono=int(input("Digite su Telefono "))
print("Su nombre es ", nombre + " Su apellido es ", apellido + " Su correo es ", correo  + " Su telefono es ", telefono)