print("Bienvenido este programa dice cuanto cuesta un terreno")
ancho=float(input("Digite el anchura "))
largo=float(input("Digite la largo "))
metro_cuadrado=int(input("Digite cuanto vale el metro cuadrado "))
promedio= int((ancho*largo) * metro_cuadrado)
print("el valor total del terreno es de $", promedio)